import Head from 'next/head'
import Header from '../components/Header'
import Banner from '../components/Banner'
import SmallCard from '../components/SmallCard'
import MediumCard from '../components/MediumCard'
import LargeCard from '../components/LargeCard'
import Footer from '../components/Footer'

// ON NEXT WE HAVE STATIC RENDER AND SERVER SIDE RENDER,
// on this home page the data don't change so much and thtas why,
// i'll use static render.

const Home = ({ exploreData, cardsData }) => {
  return (
    <div className="">
      <Head>
        <title>Walison Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header animated/>

      <div className='bg-black h-[410px] sm:h-[510px] lg:h-[610px] xl-h[710px] 2xl:h-[810px]'>
        <Banner />
      </div>

      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6'>
          <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>

          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {
              exploreData?.map(({ id, img, distance, location }) => (
                <SmallCard
                  key={id}
                  img={img}
                  distance={distance}
                  location={location}
                />
              ))
            }
          </div>
        </section>

        <section>
          <h2 className='text-4xl font-semibold py-5'>Live Anywhere</h2>

          <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3'>
            {
              cardsData?.map(({ id, img, title }) => (
                <MediumCard
                  key={id}
                  img={img}
                  title={title}
                />
              ))
            }
          </div>
        </section>

        <section>
          <LargeCard
            img="https://links.papareact.com/4cj"
            title="The Greatest Outdoors"
            description="Wishlists curated by Airbnb"
            buttonText="Get Inspired"
          />
        </section>
      </main>

      <Footer />
    </div>
  )
}

export const getStaticProps = async () => {
  const exploreData = await fetch('https://airbnb-api.herokuapp.com/api/explorePlaces')
    .then((response) => response.json())

    const cardsData = await fetch('https://airbnb-api.herokuapp.com/api/liveAnywhere')
    .then((response) => response.json())

  return {
    props: {
      exploreData,
      cardsData
    }
  }
}

export default Home
